version: "2.0"

services:
    tzero:
        image: tzero:public
        container_name: tzero-public
        restart: on-failure
        build:
            context: .
            dockerfile: Dockerfile
        volumes:
            - /var/bots/T-Zero:/app/data:rw
        working_dir: /app
        entrypoint: /app/binaries/bin/T-Zero
